project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: false

website:
  title: "Robótica 2025"
  margin-header: |
      ## [Universidad Nacional del Litoral](https://www.unl.edu.ar/) (UNL) \
      ### [Facultad de Ingeniería y Ciencias Hídricas](https://www.fich.unl.edu.ar/) (FICH) \
      **Tecnicatura en Automatizaicón y Robótica (TUAR)**
  bread-crumbs: true

format:
    html:
        page-layout: full