project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: false

website:
  title: "Robótica 2025"
  sidebar:
    # logo: https://sinc.unl.edu.ar/wp-content/themes/sinci/img/sinc-logo.png
    logo-alt: "sinc(i) - UNL - CONICET"
    search: false
    alignment: center
    border: true
    header: |
      ## [Universidad Nacional del Litoral](https://www.unl.edu.ar/) (UNL) \
      ### [Facultad de Ingeniería y Ciencias Hídricas](https://www.fich.unl.edu.ar/) (FICH) <br> \
      **Tecnicatura en Automatización y Robótica (TUAR)** <br> \
      ![](https://sinc.unl.edu.ar/wp-content/themes/sinci/img/sinc-logo.png)

  bread-crumbs: true

format:
  html:
    page-layout: full
    theme: litera