---
title: "Rob贸tica 2025"
page-navigation: false
anchor-sections: false
format:
    html:
        html-table-processing: none
---

---

# Intro

- **Carreras en FICH**: Tecnicatura en automatizaci贸n y rob贸tica
- **Extensi贸n**: Anual
- **Carga Horaria**: 120hs
- **Sitio**: [Rob贸tica 2025](https://acapovilla.github.io/robotica-2025/)
- **Docente**:
    - *Capovilla, Agust铆n* ([`acapovilla@sinc.unl.edu.ar`](mailto:acapovilla@sinc.unl.edu.ar))

<!-- # R茅gimen de aprobaci贸n y promoci贸n -->

<!-- # Programa -->

# Clases

::: {.callout-note title=""}
El siguiente cronograma ser谩 actualizado con el correr del cursado 
:::

| Semana | Fecha | Tema | Slides | Lab |
|:------:|--------|--------|:------:|:------:|
|1 | 17/03 | Introducci贸n a la Rob贸tica. Organizaci贸n de la materia. Herramientas de trabajo. | [ワ](/clases/01 "Slides"){aria-label="Clase 1 slides"} |
|2  | 24/03 | Feriado 24 de Marzo - D铆a nacional de la memoria por la verdad y la justicia | |
|3  | 31/03 | ROS2: Definici贸n y prop贸sito. Conceptos b谩sicos (nodos, topics, mensajes). Instalaci贸n y ejemplos b谩sicos. | [ワ](/clases/02 "Slides"){aria-label="Clase 2 slides"} | [И](/clases/02/lab.html "Lab"){aria-label="Clase 2 lab"}
|4  | 07/04 | ROS2: Componentes adicionales (contexto, par谩metros, servicios). Paquete y librer铆as. Ejercicios de aplicaci贸n. | [ワ](/clases/03 "Slides"){aria-label="Clase 3 slides"} | [И](/clases/03/lab.html "Lab"){aria-label="Clase 3 lab"}
|5  | 14/04 | Revisi贸n conceptos clase anterior. Programaci贸n de nodos, compilaci贸n y ejecuci贸n. | [ワ](/clases/04 "Slides"){aria-label="Clase 4 slides"} | [И](/clases/04/lab.html "Lab"){aria-label="Clase 4 lab"}
|6  | 21/04 | Programaci贸n Orientada a Objetos aplicada en ROS2. Ejemplos de aplicaci贸n. | [ワ](/clases/05 "Slides"){aria-label="Clase 5 slides"} | [И](/clases/05/lab.html "Lab"){aria-label="Clase 5 lab"}
|7  | 28/04 | Par谩metros en nodos y `roslaunch`, programaci贸n y ventajas de uso en proyectos de ROS2. Logging. Pr谩ctica integradora unidad 1.  | [ワ](/clases/06 "Slides"){aria-label="Clase 6 slides"} | [И](/clases/06/lab.html "Lab"){aria-label="Clase 6 lab"}
|8  | 05/05 | Traslaci贸n y rotaci贸n 2D. Transformaciones homog茅neas. ROS2 R.E.P. y paquete `tf2`. | [ワ](/clases/07 "Slides"){aria-label="Clase 7 slides"} | [И](/clases/07/lab.html "Lab"){aria-label="Clase 7 lab"}
|9  | 12/05 | U.R.D.F: Representaci贸n de geometr铆a de un robot. XACRO y paquete tf2. | |
|10 | 19/05 | Gazebo: Entorno de simulaci贸n. Uso conjunto con ROS2. Paquete `ros2_control` y Gazebo. | |
|11 | 26/05 | Cinem谩tica y locomoci贸n: modelo cinem谩tico de un robot diferencial | |
|12 | 02/06 | Odometr铆a: C谩lculo de posici贸n en base a modelo cinem谩tico | |
|13 | 09/06 | Percepci贸n: sensores. Clasificaci贸n y caracterizaci贸n. Tipos y ejemplos seg煤n variable a medir. | |
|14 | 16/06 | Feriado 16 de Junio - Paso a la inmortalidad del Gral. Mart铆n de G眉emes (trasladable, 17 de junio) | |
|15 | 23/06 | Revisi贸n temario clase anterior. Simulaci贸n de sensores en Gazebo | | 

: {.striped .hover tbl-colwidths="[10, 10, 60, 10, 10]"}

<!-- # Bibliograf铆a -->

<!-- # Material de estudio -->

