---
title: Clase 04 - Laboratorio
format:
    html:
        code-fold: true
        code-copy: false
        #code-overflow: wrap
        toc: true
bread-crumbs: true
page-navigation: true
---

## Parte 2: Creaci贸n de paquetes y programaci贸n de nodos

::: {.callout-note title="Paso inicial"}
Creaci贸n del `workspace`
:::

- Crear una carpeta para el `workspace` (como por ejemplo *robotica-2025*) y dentro, crear la carpeta `src`:

>```
> ...
>     robotica-2025
>         src
>...
>```

::: {.callout-tip title="Recomendaci贸n"}
Realizar este paso solo por cada proyecto individual
:::

### Creaci贸n de un paquete de ROS

>       $ ros2 pkg create --build-type ament_python <nombre_paquete>

::: {.callout-note appearance="simple"}
Dentro de `workspace/src`
:::

---------

```{.bash code-line-numbers="false"}
    $ ros2 pkg create --build-type ament_python clase_04
```

Esto generar谩 la estructura de carpetas correspondientes para un paquete de python:

> ```
>  src
>    clase_04
>        clase_04
>            __init__.py
>    resource
>        clase_04
>    test
>          ...
>    package.xml
>   锔 setup.cfg
>    setup.py
> ```

::: {.callout-tip appearance="simple"}
Completar la informaci贸n adicional en los respectivos archivos `package.xml` y `setup.py`
:::

#### Compilaci贸n

```{.bash code-line-numbers="false"}
    $ colcon build
```

::: {.callout-warning appearance="simple"}
Siempre ejecutar este comando dentro de `workspace`
:::

::: {.callout-tip appearance="simple"}
Cuando quieras compilar un solo paquete usa la opci贸n `--packages-select`
:::

Se generar谩n las carpetas adicionales en el `workspace`:

> ```
>  ...
>      robotica-2025
>          src
>          build      猬锔
>          install    猬锔
>          log        猬锔
> ...
> ```


---------

### Programaci贸n de un nodo

- #### Importar la librer铆a de Python de ROS2

```python
import rclpy
```

- #### Inicializar la comunicaci贸n con ROS

```python
rclpy.init(args=args)
```

- #### Crear el nodo

>       rclpy.create_node('<nombre_nodo>')

------

```python
nodo = rclpy.create_node('publicador')
```

- #### Crear el publicador

>       <nodo>.create_publisher(<tipo_mensaje>, '<nombre_topic>', <tama帽o_cola>)

------

```python
pub = nodo.create_publisher(String, 'chat', 10)
```

- #### Crear un timer

>       <nodo>.create_timer(<periodo_en_seg>, <funcion_callback>)

------

```python
timer = nodo.create_timer(1, timer_callback)
```

- #### Continuar ejecuci贸n de ROS

>       rclpy.spin(<nodo>)

------

```python
rclpy.spin(nodo)
```

- #### Finalizar la ejecuci贸n

```python
rclpy.shutdown()
```

------

#### Programar el nodo publicador

::: {.callout-note appearance="simple"}
Dentro de la carpeta correspondiente: `**/src/<nombre_paquete>/<nombre_paquete>`
:::

```{.python code-fold="true" code-line-numbers="true" filename="nodo_publicador.py"}
import rclpy

# Importar el tipo de mensaje String
from std_msgs.msg import String

def main(args=None):
    # 1. Inicializaci贸n
    rclpy.init(args=args)

    # 2. Creaci贸n de nodo
    # nodo = ...

    # 2.1 Creaci贸n de publisher
    # pub = ...

    # 2.2 Creaci贸n de mensaje
    msg = String()

    # 2.3 Programaci贸n de funci贸n de callback
    def timer_callback():
        # Completar el campo 'data' del mensaje 
        msg.data = 'Mensaje de prueba'

        # Publicar el mensaje
        pub.publish(msg)

    # 2.4 Creaci贸n del timer
    # ...

    # 3. Procesamiento de mensajes y callback
    rclpy.spin(nodo)

    # 4. Finalizaci贸n 
    rclpy.shutdown()


if __name__ == '__main__':
    main()
```

---------

#### Dependencias

Para a帽adir dependencias a un paquete, modificar el archivo `package.xml`

```{.xml code-line-numbers=3-4}
<package format="3">
    ...
    <exec_depend>rclpy</exec_depend>
    <exec_depend>std_msgs</exec_depend>
    ...
</package>
```

Instalar dependencias:

```{.bash code-line-numbers="false"}
    $ rosdep install -i --from-path src -y
```

::: {.callout-warning appearance="simple"}
Siempre ejecutar este comando dentro de `workspace`
:::

---------

#### Agregar un `entrypoint` o ejecutable

Para a帽adir un ejecutable en un paquete de Python, modificar el archivo `setup.py`

>       entry_points={
>            'console_scripts': [
>                    '<nombre_ejecutable> = <nombre_paquete>.<nombre_archivo>:main',
>            ],
>       },


```python
setup(
    ...
    entry_points={
            'console_scripts': [
                    'publicar = clase_04.nodo_publicador:main',
            ],
    },
)
```

---------

### Verificaci贸n del funcionamiento

::: {.callout-note appearance="simple"}
Recuerda compilar el paquete
:::

::: {.callout-note appearance="simple"}
Recuerda configurar el entorno local:
```{.bash code-line-numbers="false"}
    $ source install/setup.bash
```
:::

#### Ejecutar

::: {.callout-tip title="Para ejecutar"}
        $ ros2 run <nombre_paquete> <nombre_ejecutable>
:::

- #### Comprobar que el nodo se encuentre en ejecuci贸n

Puedes utilizar los comandos de `ros2 node list` y `ros2 node info`

- #### Comprobar que se encuentra publicando los mensajes

Puedes utilizar los comandos de `ros2 topic list`, `ros2 topic info` y `ros2 topic echo`

---------

### Programar el nodo suscriptor

- #### Crear el suscriptor

>       <nodo>.create_subscription(<tipo_mensaje>, '<nombre_topic>', <funcion_callback>, <tama帽o_cola>)

------

```python
sub = nodo.create_subscription(String, 'chat', sub_callback, 10)
```

```{.python code-fold="true" code-line-numbers="true" filename="nodo_suscriptor.py"}
import rclpy

# Importar el tipo de mensaje String
from std_msgs.msg import String

def main(args=None):
    # 1. Inicializaci贸n
    # ...

    # 2. Creaci贸n de nodo
    # nodo = ...

    # 2.1 Programaci贸n de funci贸n de callback
    def sub_callback(msg):
        # Mostrar el mensaje en consola
        nodo.get_logger().info('Recib铆: "%s"' % msg.data)

    # 2.2 Creaci贸n de suscriptor
    # ...

    # 3. Procesamiento de mensajes y callback
    rclpy.spin(nodo)

    # 4. Finalizaci贸n 
    rclpy.shutdown()


if __name__ == '__main__':
    main()
```

- #### A帽adir un nuevo ejecutable en el archivo `setup.py`

- #### Compilar y ejecutar el nodo

- #### Verificar el funcionamiento de ambos nodos