# Clases

::: {.callout-note title=""}
El siguiente cronograma podr치 ser actualizado con el correr del cursado 
:::

| Semana | Fecha | Tema | Slides | [Lab]{title="Laboratorio"} | [T.R]{title="Taller de resoluci칩n"}  |
|:------:|--------|--------|:------:|:------:|:------:|
|1 | 17/03 | Introducci칩n a la Rob칩tica. Organizaci칩n de la materia. Herramientas de trabajo. | [游둰勇끃(/clases/01 "Slides"){aria-label="Clase 1 slides"} |
|2  | 24/03 | **Feriado 24 de Marzo - D칤a nacional de la memoria por la verdad y la justicia** | |
|3  | 31/03 | ROS2: Definici칩n y prop칩sito. Conceptos b치sicos (nodos, topics, mensajes). Instalaci칩n y ejemplos b치sicos. | [游둰勇끃(/clases/02 "Slides"){aria-label="Clase 2 slides"} | [游빍](/clases/02/lab.html "Lab"){aria-label="Clase 2 lab"}
|4  | 07/04 | ROS2: Componentes adicionales (contexto, par치metros, servicios). Paquete y librer칤as. Ejercicios de aplicaci칩n. | [游둰勇끃(/clases/03 "Slides"){aria-label="Clase 3 slides"} | [游빍](/clases/03/lab.html "Lab"){aria-label="Clase 3 lab"}
|5  | 14/04 | Revisi칩n conceptos clase anterior. Programaci칩n de nodos, compilaci칩n y ejecuci칩n. | [游둰勇끃(/clases/04 "Slides"){aria-label="Clase 4 slides"} | [游빍](/clases/04/lab.html "Lab"){aria-label="Clase 4 lab"}
|6  | 21/04 | Programaci칩n Orientada a Objetos aplicada en ROS2. Ejemplos de aplicaci칩n. | [游둰勇끃(/clases/05 "Slides"){aria-label="Clase 5 slides"} | [游빍](/clases/05/lab.html "Lab"){aria-label="Clase 5 lab"}
|7  | 28/04 | Par치metros en nodos y `roslaunch`, programaci칩n y ventajas de uso en proyectos de ROS2. Logging. Pr치ctica integradora unidad 1.  | [游둰勇끃(/clases/06 "Slides"){aria-label="Clase 6 slides"} | [游빍](/clases/06/lab.html "Lab"){aria-label="Clase 6 lab"}
|8  | 05/05 | Traslaci칩n y rotaci칩n 2D. Transformaciones homog칠neas. ROS2 R.E.P. y paquete `tf2`. | [游둰勇끃(/clases/07 "Slides"){aria-label="Clase 7 slides"} | [游빍](/clases/07/lab.html "Lab"){aria-label="Clase 7 lab"}
|9  | 12/05 | U.R.D.F: Representaci칩n de geometr칤a de un robot. Uso de XACRO, `robot_state_publisher` y `tf2`. | [游둰勇끃(/clases/08 "Slides"){aria-label="Clase 8 slides"} | | [游멆잺](/clases/08/tres.html "Taller de resoluci칩n"){aria-label="Clase 8 t.r."}
|10 | 19/05 | Gazebo: Entorno de simulaci칩n. Uso conjunto con ROS2. Paquete `ros2_control` y `gz_ros2_contol`. *Hardware interface* y controladores. | [游둰勇끃(/clases/09 "Slides"){aria-label="Clase 9 slides"} | | [游멆잺](/clases/09/tres.html "Taller de resoluci칩n"){aria-label="Clase 9 t.r."}
|11 | 26/05 | Cinem치tica y locomoci칩n: modelo cinem치tico de un robot diferencial. Cinem치tica inversa y directa. | [游둰勇끃(/clases/10 "Slides"){aria-label="Clase 10 slides"} | | [游멆잺](/clases/10/tres.html "Taller de resoluci칩n"){aria-label="Clase 10 t.r."}
|12 | 02/06 | Odometr칤a: C치lculo de posici칩n en base al modelo cinem치tico directo. | [游둰勇끃(/clases/11 "Slides"){aria-label="Clase 11 slides"} | | [游멆잺](/clases/11/tres.html "Taller de resoluci칩n"){aria-label="Clase 11 t.r."}
|13 | 09/06 | Percepci칩n: sensores. Clasificaci칩n y caracterizaci칩n. Tipos y ejemplos seg칰n variable a medir. | [游둰勇끃(/clases/12 "Slides"){aria-label="Clase 12 slides"} | | 
|14 | 16/06 | **Feriado 17 de Junio - Paso a la inmortalidad del Gral. Mart칤n de G칲emes (trasladable, 16 de junio)** | |
|15 | 23/06 | Presentaci칩n entregable 1 | |
|16 | 13/08 | Simulaci칩n de sensores en Gazebo | [游둰勇끃(/clases/13 "Slides"){aria-label="Clase 13 slides"} | [游빍](/clases/13/lab.html "Lab"){aria-label="Clase 13 lab"} |
|17 | 20/08 | Revisi칩n entregable 1 | [游둰勇끃(/clases/14 "Slides"){aria-label="Clase 14 slides"} | |
|19 | 03/09 | Caso pr치ctico simulaci칩n de sensors. C치mara. Seguidor de l칤nea. | [游둰勇끃(/clases/15 "Slides"){aria-label="Clase 15 slides"} | [游빍](/clases/15/lab.html "Lab"){aria-label="Clase 15 lab"} |
|20 | 10/09 | Caso pr치ctico simulaci칩n de sensors (cont.) | |
|21 | 17/09 | Localizaci칩n con odometr칤a. Incertidumbre y estimaci칩n de posici칩n. | [游둰勇끃(/clases/16 "Slides"){aria-label="Clase 16 slides"} | [游빍](/clases/16/lab.html "Lab"){aria-label="Clase 16 lab"} |
|23 | 01/10 | Dise침o, an치lisis y programaci칩n de un controlador a lazo cerrado, sin evasi칩n de obst치culos | [游둰勇끃(/clases/17 "Slides"){aria-label="Clase 17 slides"} | [游빍](/clases/17/lab.html "Lab"){aria-label="Clase 17 lab"} |

: {.striped .hover tbl-colwidths="[8, 8, 60, 8, 8, 8]"}