on:
  workflow_dispatch:
  # push:
  #   branches: main

name: Render and Publish

jobs:
  render-and-publish:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.8'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Install pdflatex and Inkscape
        run: |
          sudo apt-get update
          sudo apt-get -y install texlive-latex-base texlive-latex-extra texlive-xetex
          sudo apt-get -y install inkscape 
          which pdflatex
          which inkscape

      - name: Render and publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}